name: Playwright Tests

on:
  push:
    branches:
      - circleci-project-setup
  pull_request:
    branches:
      - circleci-project-setup
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.47.0-jammy

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: npm test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
